Repository nverma42/Chatbot, pull requests merged in 2024-11, with the labels that each got.

#3 Added a new class for emotional response.
  Emotional_Response.py
Labels: enhancement

#5 Summarization engine
  conversation_chatbot_main.py
  emotional_response.py
  mental_health_chatbot.py
  summarization_engine.py
Labels: good first issue, Refactoring Project

#4 Refactor and integration
  Emotional_Response.py
  conversation_chatbot_main.py
  data/test.csv
  mental_health_chatbot.py
Labels: enhancement, New Feature, Refactoring Project

#7 Model Tuning
  EvalMetrics.xlsx
  conversation_chatbot_main.py
  emotional_response.py
  mental_health_chatbot.py
Labels: New Feature, Refactoring Project, New features
